meta_product_name: "Eat Better"
meta_title: "Eat Better - Manger mieux & local"
meta_description: "Tous les petits producteurs autours de chez vous!"
meta_image: "cover.png" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
